[
    uuid(15aea4d8-222c-4b42-9225-63a7277811ae),
    version(1.0)
]
interface moonshot
{
    int moonshot_get_identity_rpc ([in, string] const char *nai,
                                   [in, string] const char *password,
                                   [in, string] const char *certificate,
                                   [out, string] char **nai_out,
                                   [out, string] char **password_out,
                                   [out, string] char **server_certificate_hash,
                                   [out, string] char **ca_certificate,
                                   [out, string] char **subject_name_constraint,
                                   [out, string] char **subject_alt_name_constraint);

    int moonshot_get_default_identity_rpc ([out, string] char **nai_out,
                                           [out, string] char **password_out,
                                           [out, string] char **server_certificate_hash,
                                           [out, string] char **ca_certificate,
                                           [out, string] char **subject_name_constraint,
                                           [out, string] char **subject_alt_name_constraint);

    int moonshot_install_id_card_rpc ([in, string] const char *display_name,
                                      [in, string] const char *user_name,
                                      [in, string] const char *password,
                                      [in, string] const char *realm,
                                      [size_is(rules_patterns_length), in, string] char *rules_patterns[*],
                                      int rules_patterns_length,
                                      [size_is(rules_always_confirm_length), in, string] char *rules_always_confirm[*],
                                      int rules_always_confirm_length,
                                      [size_is(services_length), in, string] char *services[*],
                                      int services_length,
                                      [in, string] const char *ca_cert,
                                      [in, string] const char *subject,
                                      [in, string] const char *subject_alt,
                                      [in, string] const char *server_cert,
                                      int force_flat_file_store);
}
