variables:
  DOCKER_DRIVER: overlay2

stages:
- build

before_script:
  - rm -fr build SOURCES RPMS

.debiancommon: &debiancommon
  stage: build
  tags:
    - moonshot
  script:
    - apt-get -y update && apt-get -y dist-upgrade
    - dch -l "b$CI_PIPELINE_ID" "Include job ID"
    - sh autogen.sh
    - make dist
    - mv moonshot-ui-1.1.0.tar.xz ../moonshot-ui_1.1.0.orig.tar.xz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
  artifacts:
    paths:
        - build/*.deb

.centoscommon: &centoscommon
  stage: build
  tags:
    - moonshot
  script:
    - yum -y upgrade
    - sed -i "s/\(.\)%{?dist}/\1b$CI_PIPELINE_ID%{?dist}/g" moonshot-ui.spec.in
    - sh autogen.sh
    - make dist
    - mkdir -p SOURCES
    - mv -f moonshot-ui-*tar.xz SOURCES
    - rpmbuild -bb moonshot-ui.spec --define "_topdir `pwd`"
    - for i in RPMS/x86_64/*.rpm; do curl --user "$NEXUS_USER:$NEXUS_PWD" -f --upload-file "$i"  https://nexus.ci.ti.ja.net/repository/moonshot/$CI_JOB_NAME/; done
  artifacts:
    paths:
      - RPMS

centos6:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/centos6:latest
  <<: *centoscommon

centos7:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/centos7:latest
  <<: *centoscommon

debian8:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/debian8:latest
  <<: *debiancommon

debian9:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/debian9:latest
  <<: *debiancommon

ubuntu14:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu14:latest
  <<: *debiancommon

ubuntu16:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu16:latest
  <<: *debiancommon

ubuntu18:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu18:latest
  <<: *debiancommon
