variables:
  DOCKER_DRIVER: overlay2

stages:
- build

before_script:
  - rm -fr build SOURCES RPMS apks

.debiancommon: &debiancommon
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - sed -i "s/DIST/$CI_JOB_NAME.$CI_PIPELINE_ID/g" debian/changelog
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb ../*.dsc ../*tar* build
  artifacts:
    expire_in: 6 months
    paths:
        - build/*

.centoscommon: &centoscommon
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - sed -i "s/\(.\)%{?dist}/\1.$CI_PIPELINE_ID%{?dist}/g" moonshot-ui.spec.in
    - sh autogen.sh
    - make dist
    - mkdir -p SOURCES
    - mv -f moonshot-ui-*tar.xz SOURCES
    - rpmbuild -ba moonshot-ui.spec --define "_topdir `pwd`"
  artifacts:
    expire_in: 6 months
    paths:
        - RPMS
        - SRPMS

.alpinecommon: &alpinecommon
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - cp $APKBUILD APKBUILD.in
    - sed -i "s/pkgrel=0/pkgrel=$CI_PIPELINE_ID/g" APKBUILD.in
    - cp vapi/libsecret-1.vapi.dis vapi/libsecret-1.vapi
    - adduser -D tmpuser -s /bin/sh
    - adduser tmpuser abuild
    - sh autogen.sh
    - sed -i "s/GZIP_ENV = --best//g" Makefile.in
    - ./configure
    - make dist
    - chown tmpuser . -R
    - sudo -u tmpuser abuild checksum
    - sudo -u tmpuser abuild-keygen -an
    - sudo -u tmpuser abuild -r
    - mkdir apks
    - mv /home/tmpuser/packages/moonshot/* apks
  artifacts:
    expire_in: 6 months
    paths:
        - apks/*/*.apk

centos6:
  image: $DOCKER_REGISTRY_URL/centos6:latest
  <<: *centoscommon

centos7:
  image: $DOCKER_REGISTRY_URL/centos7:latest
  <<: *centoscommon

debian8:
  image: $DOCKER_REGISTRY_URL/debian8:latest
  <<: *debiancommon

debian9:
  image: $DOCKER_REGISTRY_URL/debian9:latest
  <<: *debiancommon

debian10:
  image: $DOCKER_REGISTRY_URL/debian10:latest
  <<: *debiancommon

raspbian8:
  image: $DOCKER_REGISTRY_URL/raspbian8:latest
  when: manual
  <<: *debiancommon

raspbian9:
  image: $DOCKER_REGISTRY_URL/raspbian9:latest
  when: manual
  <<: *debiancommon

raspbian10:
  image: $DOCKER_REGISTRY_URL/raspbian10:latest
  when: manual
  <<: *debiancommon

ubuntu16:
  image: $DOCKER_REGISTRY_URL/ubuntu16:latest
  <<: *debiancommon

ubuntu18:
  image: $DOCKER_REGISTRY_URL/ubuntu18:latest
  <<: *debiancommon

alpine38:
  image: $DOCKER_REGISTRY_URL/alpine38:latest
  variables:
    APKBUILD: APKBUILD.in.alpine38
  <<: *alpinecommon

alpine38_armhf:
  image: $DOCKER_REGISTRY_URL/alpine38_arm:latest
  when: manual
  variables:
    APKBUILD: APKBUILD.in.alpine38
  <<: *alpinecommon

alpine39:
  image: $DOCKER_REGISTRY_URL/alpine39:latest
  variables:
    APKBUILD: APKBUILD.in.alpine39
  <<: *alpinecommon

alpine39_armhf:
  image: $DOCKER_REGISTRY_URL/alpine39_arm:latest
  when: manual
  variables:
    APKBUILD: APKBUILD.in.alpine39
  <<: *alpinecommon
