variables:
  DOCKER_DRIVER: overlay2

stages:
- build

.debiancommon: &debiancommon
  stage: build
  except:
    - tags
  script:
    - sed -i "s/DIST/$CI_JOB_NAME/g" debian/changelog
    - debuild -us -uc
    - mkdir build
    - mv ../*.deb ../*.dsc ../*tar* build
  artifacts:
    expire_in: 6 months
    paths:
        - build/*

.centoscommon: &centoscommon
  stage: build
  except:
    - tags
  script:
    - sh autogen.sh
    - make dist
    - mkdir -p SOURCES
    - mv -f moonshot-ui-*tar.xz SOURCES
    - rpmbuild -ba moonshot-ui.spec --define "_topdir `pwd`"
  artifacts:
    expire_in: 6 months
    paths:
        - RPMS
        - SRPMS

.alpinecommon: &alpinecommon
  stage: build
  except:
    - tags
  script:
    - cp vapi/libsecret-1.vapi.dis vapi/libsecret-1.vapi
    - adduser -D tmpuser -s /bin/sh
    - adduser tmpuser abuild
    - sh autogen.sh
    - sed -i "s/GZIP_ENV = --best//g" Makefile.in
    - ./configure
    - make dist
    - chown tmpuser . -R
    - sudo -u tmpuser abuild checksum
    - sudo -u tmpuser abuild-keygen -an
    - sudo -u tmpuser abuild -r
    - mkdir apks
    - mv /home/tmpuser/packages/*/* apks
  artifacts:
    expire_in: 6 months
    paths:
        - apks/*/*.apk

centos7:
  image: $DOCKER_REGISTRY_URL/centos7:latest
  <<: *centoscommon

centos8:
  image: $DOCKER_REGISTRY_URL/centos8:latest
  <<: *centoscommon

debian9:
  image: $DOCKER_REGISTRY_URL/debian9:latest
  <<: *debiancommon

debian10:
  image: $DOCKER_REGISTRY_URL/debian10:latest
  <<: *debiancommon

debian11:
  image: $DOCKER_REGISTRY_URL/debian11:latest
  <<: *debiancommon

raspbian9:
  image: $DOCKER_REGISTRY_URL/raspbian9:latest
  <<: *debiancommon
  tags:
    - arm

raspbian10:
  image: $DOCKER_REGISTRY_URL/raspbian10:latest
  <<: *debiancommon
  tags:
    - arm

raspbian11:
  image: $DOCKER_REGISTRY_URL/raspbian11:latest
  <<: *debiancommon
  tags:
    - arm

ubuntu18:
  image: $DOCKER_REGISTRY_URL/ubuntu18:latest
  <<: *debiancommon

ubuntu20:
  image: $DOCKER_REGISTRY_URL/ubuntu20:latest
  <<: *debiancommon

alpine311:
  image: $DOCKER_REGISTRY_URL/alpine311:latest
  <<: *alpinecommon

alpine311_armhf:
  image: $DOCKER_REGISTRY_URL/alpine311_arm:latest
  <<: *alpinecommon
  tags:
    - arm

alpine313:
  image: $DOCKER_REGISTRY_URL/alpine313:latest
  <<: *alpinecommon

alpine313_armhf:
  image: $DOCKER_REGISTRY_URL/alpine313_arm:latest
  <<: *alpinecommon
  tags:
    - arm
