variables:
  DOCKER_DRIVER: overlay2

stages:
- build

before_script:
  - rm -fr build SOURCES RPMS

centos6:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/centos6:latest
  stage: build
  tags:
    - moonshot
  script:
    - sed -i "s/1%{?dist}/1b$CI_PIPELINE_ID%ist}/g" moonshot-ui.spec.in
    - sh autogen.sh
    - make dist
    - mkdir -p SOURCES
    - mv -f moonshot-ui-*tar.xz SOURCES
    - rpmbuild -bb moonshot-ui.spec --define "_topdir `pwd`"
  artifacts:
    paths:
        - RPMS

centos7:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/centos7:latest
  stage: build
  tags:
    - moonshot
  script:
    - sed -i "s/1%{?dist}/1b$CI_PIPELINE_ID%ist}/g" moonshot-ui.spec.in
    - sh autogen.sh
    - make dist
    - mkdir -p SOURCES
    - mv -f moonshot-ui-*tar.xz SOURCES
    - rpmbuild -bb moonshot-ui.spec --define "_topdir `pwd`"
  artifacts:
    paths:
        - RPMS

debian8:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/debian8:latest
  stage: build
  tags:
    - moonshot
  script:
    - dch -l "b$CI_PIPELINE_ID" "Include job ID"
    - sh autogen.sh
    - make dist
    - mv moonshot-ui-1.1.0.tar.xz ../moonshot-ui_1.1.0.orig.tar.xz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
  artifacts:
    paths:
        - build/*.deb

debian9:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/debian9:latest
  stage: build
  tags:
    - moonshot
  script:
    - dch -l "b$CI_PIPELINE_ID" "Include job ID"
    - sh autogen.sh
    - make dist
    - mv moonshot-ui-1.1.0.tar.xz ../moonshot-ui_1.1.0.orig.tar.xz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
  artifacts:
    paths:
        - build/*.deb

ubuntu14:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu14:latest
  stage: build
  tags:
    - moonshot
  script:
    - dch -l "b$CI_PIPELINE_ID" "Include job ID"
    - sh autogen.sh
    - make dist
    - mv moonshot-ui-1.1.0.tar.xz ../moonshot-ui_1.1.0.orig.tar.xz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
  artifacts:
    paths:
        - build/*.deb

ubuntu16:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu16:latest
  stage: build
  tags:
    - moonshot
  script:
    - dch -l "b$CI_PIPELINE_ID" "Include job ID"
    - sh autogen.sh
    - make dist
    - mv moonshot-ui-1.1.0.tar.xz ../moonshot-ui_1.1.0.orig.tar.xz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
  artifacts:
    paths:
        - build/*.deb

ubuntu18:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu18:latest
  stage: build
  tags:
    - moonshot
  script:
    - dch -l "b$CI_PIPELINE_ID" "Include job ID"
    - sh autogen.sh
    - make dist
    - mv moonshot-ui-1.1.0.tar.xz ../moonshot-ui_1.1.0.orig.tar.xz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
  artifacts:
    paths:
        - build/*.deb
