/* moonshot-custom-vbox.c generated by valac 0.10.4, the Vala compiler
 * generated from moonshot-custom-vbox.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>


#define TYPE_CUSTOM_VBOX (custom_vbox_get_type ())
#define CUSTOM_VBOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CUSTOM_VBOX, CustomVBox))
#define CUSTOM_VBOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CUSTOM_VBOX, CustomVBoxClass))
#define IS_CUSTOM_VBOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CUSTOM_VBOX))
#define IS_CUSTOM_VBOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CUSTOM_VBOX))
#define CUSTOM_VBOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CUSTOM_VBOX, CustomVBoxClass))

typedef struct _CustomVBox CustomVBox;
typedef struct _CustomVBoxClass CustomVBoxClass;
typedef struct _CustomVBoxPrivate CustomVBoxPrivate;

#define TYPE_ID_CARD_WIDGET (id_card_widget_get_type ())
#define ID_CARD_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ID_CARD_WIDGET, IdCardWidget))
#define ID_CARD_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ID_CARD_WIDGET, IdCardWidgetClass))
#define IS_ID_CARD_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ID_CARD_WIDGET))
#define IS_ID_CARD_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ID_CARD_WIDGET))
#define ID_CARD_WIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ID_CARD_WIDGET, IdCardWidgetClass))

typedef struct _IdCardWidget IdCardWidget;
typedef struct _IdCardWidgetClass IdCardWidgetClass;

#define TYPE_MAIN_WINDOW (main_window_get_type ())
#define MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN_WINDOW, MainWindow))
#define MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN_WINDOW, MainWindowClass))
#define IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN_WINDOW))
#define IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN_WINDOW))
#define MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN_WINDOW, MainWindowClass))

typedef struct _MainWindow MainWindow;
typedef struct _MainWindowClass MainWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _MainWindowPrivate MainWindowPrivate;

#define TYPE_IDENTITIES_MANAGER (identities_manager_get_type ())
#define IDENTITIES_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_IDENTITIES_MANAGER, IdentitiesManager))
#define IDENTITIES_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_IDENTITIES_MANAGER, IdentitiesManagerClass))
#define IS_IDENTITIES_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_IDENTITIES_MANAGER))
#define IS_IDENTITIES_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_IDENTITIES_MANAGER))
#define IDENTITIES_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_IDENTITIES_MANAGER, IdentitiesManagerClass))

typedef struct _IdentitiesManager IdentitiesManager;
typedef struct _IdentitiesManagerClass IdentitiesManagerClass;

#define TYPE_IDENTITY_REQUEST (identity_request_get_type ())
#define IDENTITY_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_IDENTITY_REQUEST, IdentityRequest))
#define IDENTITY_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_IDENTITY_REQUEST, IdentityRequestClass))
#define IS_IDENTITY_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_IDENTITY_REQUEST))
#define IS_IDENTITY_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_IDENTITY_REQUEST))
#define IDENTITY_REQUEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_IDENTITY_REQUEST, IdentityRequestClass))

typedef struct _IdentityRequest IdentityRequest;
typedef struct _IdentityRequestClass IdentityRequestClass;
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))

struct _CustomVBox {
	GtkVBox parent_instance;
	CustomVBoxPrivate * priv;
};

struct _CustomVBoxClass {
	GtkVBoxClass parent_class;
};

struct _CustomVBoxPrivate {
	IdCardWidget* _current_idcard;
	MainWindow* main_window;
};

struct _MainWindow {
	GtkWindow parent_instance;
	MainWindowPrivate * priv;
	IdentitiesManager* identities_manager;
	GQueue* request_queue;
};

struct _MainWindowClass {
	GtkWindowClass parent_class;
};


static gpointer custom_vbox_parent_class = NULL;

GType custom_vbox_get_type (void) G_GNUC_CONST;
GType id_card_widget_get_type (void) G_GNUC_CONST;
GType main_window_get_type (void) G_GNUC_CONST;
#define CUSTOM_VBOX_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_CUSTOM_VBOX, CustomVBoxPrivate))
enum  {
	CUSTOM_VBOX_DUMMY_PROPERTY,
	CUSTOM_VBOX_CURRENT_IDCARD
};
CustomVBox* custom_vbox_new (MainWindow* window, gboolean homogeneous, gint spacing);
CustomVBox* custom_vbox_construct (GType object_type, MainWindow* window, gboolean homogeneous, gint spacing);
void custom_vbox_receive_expanded_event (CustomVBox* self, IdCardWidget* id_card_widget);
void id_card_widget_collapse (IdCardWidget* self);
void custom_vbox_set_current_idcard (CustomVBox* self, IdCardWidget* value);
IdCardWidget* custom_vbox_get_current_idcard (CustomVBox* self);
GType identities_manager_get_type (void) G_GNUC_CONST;
GType identity_request_get_type (void) G_GNUC_CONST;
GtkButton* id_card_widget_get_send_button (IdCardWidget* self);
void custom_vbox_add_id_card_widget (CustomVBox* self, IdCardWidget* id_card_widget);
void custom_vbox_remove_id_card_widget (CustomVBox* self, IdCardWidget* id_card_widget);
static void custom_vbox_finalize (GObject* obj);
static void custom_vbox_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void custom_vbox_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);



static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


CustomVBox* custom_vbox_construct (GType object_type, MainWindow* window, gboolean homogeneous, gint spacing) {
	CustomVBox * self;
	MainWindow* _tmp0_;
	g_return_val_if_fail (window != NULL, NULL);
	self = g_object_newv (object_type, 0, NULL);
	self->priv->main_window = (_tmp0_ = _g_object_ref0 (window), _g_object_unref0 (self->priv->main_window), _tmp0_);
	gtk_box_set_homogeneous ((GtkBox*) self, homogeneous);
	gtk_box_set_spacing ((GtkBox*) self, spacing);
	return self;
}


CustomVBox* custom_vbox_new (MainWindow* window, gboolean homogeneous, gint spacing) {
	return custom_vbox_construct (TYPE_CUSTOM_VBOX, window, homogeneous, spacing);
}


void custom_vbox_receive_expanded_event (CustomVBox* self, IdCardWidget* id_card_widget) {
	GList* list;
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	g_return_if_fail (id_card_widget != NULL);
	list = gtk_container_get_children ((GtkContainer*) self);
	{
		GList* id_card_collection;
		GList* id_card_it;
		id_card_collection = list;
		for (id_card_it = id_card_collection; id_card_it != NULL; id_card_it = id_card_it->next) {
			GtkWidget* id_card;
			id_card = _g_object_ref0 ((GtkWidget*) id_card_it->data);
			{
				if (id_card != GTK_WIDGET (id_card_widget)) {
					id_card_widget_collapse (ID_CARD_WIDGET (id_card));
				}
				_g_object_unref0 (id_card);
			}
		}
	}
	custom_vbox_set_current_idcard (self, id_card_widget);
	if (self->priv->_current_idcard != NULL) {
		_tmp0_ = self->priv->main_window->request_queue->length > 0;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		gtk_widget_set_sensitive ((GtkWidget*) id_card_widget_get_send_button (self->priv->_current_idcard), TRUE);
	}
	_g_list_free0 (list);
}


void custom_vbox_add_id_card_widget (CustomVBox* self, IdCardWidget* id_card_widget) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (id_card_widget != NULL);
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) id_card_widget, FALSE, FALSE, 0);
}


void custom_vbox_remove_id_card_widget (CustomVBox* self, IdCardWidget* id_card_widget) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (id_card_widget != NULL);
	gtk_container_remove ((GtkContainer*) self, (GtkWidget*) id_card_widget);
}


IdCardWidget* custom_vbox_get_current_idcard (CustomVBox* self) {
	IdCardWidget* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_current_idcard;
	return result;
}


void custom_vbox_set_current_idcard (CustomVBox* self, IdCardWidget* value) {
	IdCardWidget* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_current_idcard = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_current_idcard), _tmp0_);
	g_object_notify ((GObject *) self, "current-idcard");
}


static void custom_vbox_class_init (CustomVBoxClass * klass) {
	custom_vbox_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CustomVBoxPrivate));
	G_OBJECT_CLASS (klass)->get_property = custom_vbox_get_property;
	G_OBJECT_CLASS (klass)->set_property = custom_vbox_set_property;
	G_OBJECT_CLASS (klass)->finalize = custom_vbox_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), CUSTOM_VBOX_CURRENT_IDCARD, g_param_spec_object ("current-idcard", "current-idcard", "current-idcard", TYPE_ID_CARD_WIDGET, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void custom_vbox_instance_init (CustomVBox * self) {
	self->priv = CUSTOM_VBOX_GET_PRIVATE (self);
	self->priv->_current_idcard = NULL;
}


static void custom_vbox_finalize (GObject* obj) {
	CustomVBox * self;
	self = CUSTOM_VBOX (obj);
	_g_object_unref0 (self->priv->_current_idcard);
	_g_object_unref0 (self->priv->main_window);
	G_OBJECT_CLASS (custom_vbox_parent_class)->finalize (obj);
}


GType custom_vbox_get_type (void) {
	static volatile gsize custom_vbox_type_id__volatile = 0;
	if (g_once_init_enter (&custom_vbox_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CustomVBoxClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) custom_vbox_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CustomVBox), 0, (GInstanceInitFunc) custom_vbox_instance_init, NULL };
		GType custom_vbox_type_id;
		custom_vbox_type_id = g_type_register_static (GTK_TYPE_VBOX, "CustomVBox", &g_define_type_info, 0);
		g_once_init_leave (&custom_vbox_type_id__volatile, custom_vbox_type_id);
	}
	return custom_vbox_type_id__volatile;
}


static void custom_vbox_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	CustomVBox * self;
	self = CUSTOM_VBOX (object);
	switch (property_id) {
		case CUSTOM_VBOX_CURRENT_IDCARD:
		g_value_set_object (value, custom_vbox_get_current_idcard (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void custom_vbox_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	CustomVBox * self;
	self = CUSTOM_VBOX (object);
	switch (property_id) {
		case CUSTOM_VBOX_CURRENT_IDCARD:
		custom_vbox_set_current_idcard (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}




