/* moonshot-idcard-store.c generated by valac 0.10.4, the Vala compiler
 * generated from moonshot-idcard-store.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gee.h>


#define TYPE_IIDENTITY_CARD_STORE (iidentity_card_store_get_type ())
#define IIDENTITY_CARD_STORE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_IIDENTITY_CARD_STORE, IIdentityCardStore))
#define IS_IIDENTITY_CARD_STORE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_IIDENTITY_CARD_STORE))
#define IIDENTITY_CARD_STORE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_IIDENTITY_CARD_STORE, IIdentityCardStoreIface))

typedef struct _IIdentityCardStore IIdentityCardStore;
typedef struct _IIdentityCardStoreIface IIdentityCardStoreIface;

#define TYPE_ID_CARD (id_card_get_type ())
#define ID_CARD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ID_CARD, IdCard))
#define ID_CARD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ID_CARD, IdCardClass))
#define IS_ID_CARD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ID_CARD))
#define IS_ID_CARD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ID_CARD))
#define ID_CARD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ID_CARD, IdCardClass))

typedef struct _IdCard IdCard;
typedef struct _IdCardClass IdCardClass;

struct _IIdentityCardStoreIface {
	GTypeInterface parent_iface;
	void (*add_card) (IIdentityCardStore* self, IdCard* card);
	void (*remove_card) (IIdentityCardStore* self, IdCard* card);
	void (*update_card) (IIdentityCardStore* self, IdCard* card);
	GeeLinkedList* (*get_card_list) (IIdentityCardStore* self);
};



GType id_card_get_type (void) G_GNUC_CONST;
GType iidentity_card_store_get_type (void) G_GNUC_CONST;
void iidentity_card_store_add_card (IIdentityCardStore* self, IdCard* card);
void iidentity_card_store_remove_card (IIdentityCardStore* self, IdCard* card);
void iidentity_card_store_update_card (IIdentityCardStore* self, IdCard* card);
GeeLinkedList* iidentity_card_store_get_card_list (IIdentityCardStore* self);



void iidentity_card_store_add_card (IIdentityCardStore* self, IdCard* card) {
	IIDENTITY_CARD_STORE_GET_INTERFACE (self)->add_card (self, card);
}


void iidentity_card_store_remove_card (IIdentityCardStore* self, IdCard* card) {
	IIDENTITY_CARD_STORE_GET_INTERFACE (self)->remove_card (self, card);
}


void iidentity_card_store_update_card (IIdentityCardStore* self, IdCard* card) {
	IIDENTITY_CARD_STORE_GET_INTERFACE (self)->update_card (self, card);
}


GeeLinkedList* iidentity_card_store_get_card_list (IIdentityCardStore* self) {
	return IIDENTITY_CARD_STORE_GET_INTERFACE (self)->get_card_list (self);
}


static void iidentity_card_store_base_init (IIdentityCardStoreIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType iidentity_card_store_get_type (void) {
	static volatile gsize iidentity_card_store_type_id__volatile = 0;
	if (g_once_init_enter (&iidentity_card_store_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (IIdentityCardStoreIface), (GBaseInitFunc) iidentity_card_store_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType iidentity_card_store_type_id;
		iidentity_card_store_type_id = g_type_register_static (G_TYPE_INTERFACE, "IIdentityCardStore", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (iidentity_card_store_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&iidentity_card_store_type_id__volatile, iidentity_card_store_type_id);
	}
	return iidentity_card_store_type_id__volatile;
}




