/* moonshot-identities-manager.c generated by valac 0.10.4, the Vala compiler
 * generated from moonshot-identities-manager.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_IDENTITY_MANAGER_MODEL (identity_manager_model_get_type ())
#define IDENTITY_MANAGER_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_IDENTITY_MANAGER_MODEL, IdentityManagerModel))
#define IDENTITY_MANAGER_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_IDENTITY_MANAGER_MODEL, IdentityManagerModelClass))
#define IS_IDENTITY_MANAGER_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_IDENTITY_MANAGER_MODEL))
#define IS_IDENTITY_MANAGER_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_IDENTITY_MANAGER_MODEL))
#define IDENTITY_MANAGER_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_IDENTITY_MANAGER_MODEL, IdentityManagerModelClass))

typedef struct _IdentityManagerModel IdentityManagerModel;
typedef struct _IdentityManagerModelClass IdentityManagerModelClass;
typedef struct _IdentityManagerModelPrivate IdentityManagerModelPrivate;

#define TYPE_IIDENTITY_CARD_STORE (iidentity_card_store_get_type ())
#define IIDENTITY_CARD_STORE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_IIDENTITY_CARD_STORE, IIdentityCardStore))
#define IS_IIDENTITY_CARD_STORE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_IIDENTITY_CARD_STORE))
#define IIDENTITY_CARD_STORE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_IIDENTITY_CARD_STORE, IIdentityCardStoreIface))

typedef struct _IIdentityCardStore IIdentityCardStore;
typedef struct _IIdentityCardStoreIface IIdentityCardStoreIface;

#define TYPE_ID_CARD (id_card_get_type ())
#define ID_CARD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ID_CARD, IdCard))
#define ID_CARD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ID_CARD, IdCardClass))
#define IS_ID_CARD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ID_CARD))
#define IS_ID_CARD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ID_CARD))
#define ID_CARD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ID_CARD, IdCardClass))

typedef struct _IdCard IdCard;
typedef struct _IdCardClass IdCardClass;

#define TYPE_IDENTITY_MANAGER_APP (identity_manager_app_get_type ())
#define IDENTITY_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_IDENTITY_MANAGER_APP, IdentityManagerApp))
#define IDENTITY_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_IDENTITY_MANAGER_APP, IdentityManagerAppClass))
#define IS_IDENTITY_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_IDENTITY_MANAGER_APP))
#define IS_IDENTITY_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_IDENTITY_MANAGER_APP))
#define IDENTITY_MANAGER_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_IDENTITY_MANAGER_APP, IdentityManagerAppClass))

typedef struct _IdentityManagerApp IdentityManagerApp;
typedef struct _IdentityManagerAppClass IdentityManagerAppClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _identity_manager_app_unref0(var) ((var == NULL) ? NULL : (var = (identity_manager_app_unref (var), NULL)))

#define TYPE_LOCAL_FLAT_FILE_STORE (local_flat_file_store_get_type ())
#define LOCAL_FLAT_FILE_STORE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LOCAL_FLAT_FILE_STORE, LocalFlatFileStore))
#define LOCAL_FLAT_FILE_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LOCAL_FLAT_FILE_STORE, LocalFlatFileStoreClass))
#define IS_LOCAL_FLAT_FILE_STORE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LOCAL_FLAT_FILE_STORE))
#define IS_LOCAL_FLAT_FILE_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LOCAL_FLAT_FILE_STORE))
#define LOCAL_FLAT_FILE_STORE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LOCAL_FLAT_FILE_STORE, LocalFlatFileStoreClass))

typedef struct _LocalFlatFileStore LocalFlatFileStore;
typedef struct _LocalFlatFileStoreClass LocalFlatFileStoreClass;

struct _IdentityManagerModel {
	GObject parent_instance;
	IdentityManagerModelPrivate * priv;
};

struct _IdentityManagerModelClass {
	GObjectClass parent_class;
};

struct _IIdentityCardStoreIface {
	GTypeInterface parent_iface;
	void (*add_card) (IIdentityCardStore* self, IdCard* card);
	void (*remove_card) (IIdentityCardStore* self, IdCard* card);
	void (*update_card) (IIdentityCardStore* self, IdCard* card);
	GeeLinkedList* (*get_card_list) (IIdentityCardStore* self);
};

struct _IdentityManagerModelPrivate {
	IIdentityCardStore* store;
	IdentityManagerApp* parent;
};


static gpointer identity_manager_model_parent_class = NULL;

GType identity_manager_model_get_type (void) G_GNUC_CONST;
GType id_card_get_type (void) G_GNUC_CONST;
GType iidentity_card_store_get_type (void) G_GNUC_CONST;
gpointer identity_manager_app_ref (gpointer instance);
void identity_manager_app_unref (gpointer instance);
GParamSpec* param_spec_identity_manager_app (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_identity_manager_app (GValue* value, gpointer v_object);
void value_take_identity_manager_app (GValue* value, gpointer v_object);
gpointer value_get_identity_manager_app (const GValue* value);
GType identity_manager_app_get_type (void) G_GNUC_CONST;
#define IDENTITY_MANAGER_MODEL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_IDENTITY_MANAGER_MODEL, IdentityManagerModelPrivate))
enum  {
	IDENTITY_MANAGER_MODEL_DUMMY_PROPERTY
};
#define IDENTITY_MANAGER_MODEL_FILE_NAME "identities.txt"
GeeLinkedList* identity_manager_model_get_card_list (IdentityManagerModel* self);
GeeLinkedList* iidentity_card_store_get_card_list (IIdentityCardStore* self);
void identity_manager_model_add_card (IdentityManagerModel* self, IdCard* card);
void iidentity_card_store_add_card (IIdentityCardStore* self, IdCard* card);
void identity_manager_model_update_card (IdentityManagerModel* self, IdCard* card);
void iidentity_card_store_update_card (IIdentityCardStore* self, IdCard* card);
void identity_manager_model_remove_card (IdentityManagerModel* self, IdCard* card);
void iidentity_card_store_remove_card (IIdentityCardStore* self, IdCard* card);
IdentityManagerModel* identity_manager_model_new (IdentityManagerApp* parent_app);
IdentityManagerModel* identity_manager_model_construct (GType object_type, IdentityManagerApp* parent_app);
LocalFlatFileStore* local_flat_file_store_new (void);
LocalFlatFileStore* local_flat_file_store_construct (GType object_type);
GType local_flat_file_store_get_type (void) G_GNUC_CONST;
static void identity_manager_model_finalize (GObject* obj);



GeeLinkedList* identity_manager_model_get_card_list (IdentityManagerModel* self) {
	GeeLinkedList* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = iidentity_card_store_get_card_list (self->priv->store);
	return result;
}


void identity_manager_model_add_card (IdentityManagerModel* self, IdCard* card) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (card != NULL);
	iidentity_card_store_add_card (self->priv->store, card);
	g_signal_emit_by_name (self, "card-list-changed");
}


void identity_manager_model_update_card (IdentityManagerModel* self, IdCard* card) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (card != NULL);
	iidentity_card_store_update_card (self->priv->store, card);
	g_signal_emit_by_name (self, "card-list-changed");
}


void identity_manager_model_remove_card (IdentityManagerModel* self, IdCard* card) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (card != NULL);
	iidentity_card_store_remove_card (self->priv->store, card);
	g_signal_emit_by_name (self, "card-list-changed");
}


static gpointer _identity_manager_app_ref0 (gpointer self) {
	return self ? identity_manager_app_ref (self) : NULL;
}


IdentityManagerModel* identity_manager_model_construct (GType object_type, IdentityManagerApp* parent_app) {
	IdentityManagerModel * self = NULL;
	IdentityManagerApp* _tmp0_;
	IIdentityCardStore* _tmp1_;
	g_return_val_if_fail (parent_app != NULL, NULL);
	self = (IdentityManagerModel*) g_object_new (object_type, NULL);
	self->priv->parent = (_tmp0_ = _identity_manager_app_ref0 (parent_app), _identity_manager_app_unref0 (self->priv->parent), _tmp0_);
	self->priv->store = (_tmp1_ = (IIdentityCardStore*) local_flat_file_store_new (), _g_object_unref0 (self->priv->store), _tmp1_);
	return self;
}


IdentityManagerModel* identity_manager_model_new (IdentityManagerApp* parent_app) {
	return identity_manager_model_construct (TYPE_IDENTITY_MANAGER_MODEL, parent_app);
}


static void identity_manager_model_class_init (IdentityManagerModelClass * klass) {
	identity_manager_model_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (IdentityManagerModelPrivate));
	G_OBJECT_CLASS (klass)->finalize = identity_manager_model_finalize;
	g_signal_new ("card_list_changed", TYPE_IDENTITY_MANAGER_MODEL, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void identity_manager_model_instance_init (IdentityManagerModel * self) {
	self->priv = IDENTITY_MANAGER_MODEL_GET_PRIVATE (self);
}


static void identity_manager_model_finalize (GObject* obj) {
	IdentityManagerModel * self;
	self = IDENTITY_MANAGER_MODEL (obj);
	_g_object_unref0 (self->priv->store);
	_identity_manager_app_unref0 (self->priv->parent);
	G_OBJECT_CLASS (identity_manager_model_parent_class)->finalize (obj);
}


GType identity_manager_model_get_type (void) {
	static volatile gsize identity_manager_model_type_id__volatile = 0;
	if (g_once_init_enter (&identity_manager_model_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (IdentityManagerModelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) identity_manager_model_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (IdentityManagerModel), 0, (GInstanceInitFunc) identity_manager_model_instance_init, NULL };
		GType identity_manager_model_type_id;
		identity_manager_model_type_id = g_type_register_static (G_TYPE_OBJECT, "IdentityManagerModel", &g_define_type_info, 0);
		g_once_init_leave (&identity_manager_model_type_id__volatile, identity_manager_model_type_id);
	}
	return identity_manager_model_type_id__volatile;
}




