/* moonshot-identity-manager-app.c generated by valac 0.10.4, the Vala compiler
 * generated from moonshot-identity-manager-app.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <config.h>


#define TYPE_IDENTITY_MANAGER_APP (identity_manager_app_get_type ())
#define IDENTITY_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_IDENTITY_MANAGER_APP, IdentityManagerApp))
#define IDENTITY_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_IDENTITY_MANAGER_APP, IdentityManagerAppClass))
#define IS_IDENTITY_MANAGER_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_IDENTITY_MANAGER_APP))
#define IS_IDENTITY_MANAGER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_IDENTITY_MANAGER_APP))
#define IDENTITY_MANAGER_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_IDENTITY_MANAGER_APP, IdentityManagerAppClass))

typedef struct _IdentityManagerApp IdentityManagerApp;
typedef struct _IdentityManagerAppClass IdentityManagerAppClass;
typedef struct _IdentityManagerAppPrivate IdentityManagerAppPrivate;

#define TYPE_IDENTITY_MANAGER_MODEL (identity_manager_model_get_type ())
#define IDENTITY_MANAGER_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_IDENTITY_MANAGER_MODEL, IdentityManagerModel))
#define IDENTITY_MANAGER_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_IDENTITY_MANAGER_MODEL, IdentityManagerModelClass))
#define IS_IDENTITY_MANAGER_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_IDENTITY_MANAGER_MODEL))
#define IS_IDENTITY_MANAGER_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_IDENTITY_MANAGER_MODEL))
#define IDENTITY_MANAGER_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_IDENTITY_MANAGER_MODEL, IdentityManagerModelClass))

typedef struct _IdentityManagerModel IdentityManagerModel;
typedef struct _IdentityManagerModelClass IdentityManagerModelClass;

#define TYPE_IDENTITY_MANAGER_VIEW (identity_manager_view_get_type ())
#define IDENTITY_MANAGER_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_IDENTITY_MANAGER_VIEW, IdentityManagerView))
#define IDENTITY_MANAGER_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_IDENTITY_MANAGER_VIEW, IdentityManagerViewClass))
#define IS_IDENTITY_MANAGER_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_IDENTITY_MANAGER_VIEW))
#define IS_IDENTITY_MANAGER_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_IDENTITY_MANAGER_VIEW))
#define IDENTITY_MANAGER_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_IDENTITY_MANAGER_VIEW, IdentityManagerViewClass))

typedef struct _IdentityManagerView IdentityManagerView;
typedef struct _IdentityManagerViewClass IdentityManagerViewClass;

#define TYPE_MOONSHOT_SERVER (moonshot_server_get_type ())
#define MOONSHOT_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MOONSHOT_SERVER, MoonshotServer))
#define MOONSHOT_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MOONSHOT_SERVER, MoonshotServerClass))
#define IS_MOONSHOT_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MOONSHOT_SERVER))
#define IS_MOONSHOT_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MOONSHOT_SERVER))
#define MOONSHOT_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MOONSHOT_SERVER, MoonshotServerClass))

typedef struct _MoonshotServer MoonshotServer;
typedef struct _MoonshotServerClass MoonshotServerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _IdentityManagerApp {
	GtkWindow parent_instance;
	IdentityManagerAppPrivate * priv;
	IdentityManagerModel* model;
};

struct _IdentityManagerAppClass {
	GtkWindowClass parent_class;
};

struct _IdentityManagerAppPrivate {
	IdentityManagerView* view;
	MoonshotServer* ipc_server;
};


static gpointer identity_manager_app_parent_class = NULL;

GType identity_manager_app_get_type (void) G_GNUC_CONST;
GType identity_manager_model_get_type (void) G_GNUC_CONST;
GType identity_manager_view_get_type (void) G_GNUC_CONST;
GType moonshot_server_get_type (void) G_GNUC_CONST;
guint moonshot_server_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
#define IDENTITY_MANAGER_APP_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_IDENTITY_MANAGER_APP, IdentityManagerAppPrivate))
enum  {
	IDENTITY_MANAGER_APP_DUMMY_PROPERTY
};
#define IDENTITY_MANAGER_APP_WINDOW_WIDTH 400
#define IDENTITY_MANAGER_APP_WINDOW_HEIGHT 500
void identity_manager_app_show (IdentityManagerApp* self);
IdentityManagerApp* identity_manager_app_new (void);
IdentityManagerApp* identity_manager_app_construct (GType object_type);
IdentityManagerModel* identity_manager_model_new (IdentityManagerApp* parent_app);
IdentityManagerModel* identity_manager_model_construct (GType object_type, IdentityManagerApp* parent_app);
IdentityManagerView* identity_manager_view_new (IdentityManagerApp* app);
IdentityManagerView* identity_manager_view_construct (GType object_type, IdentityManagerApp* app);
static void identity_manager_app_init_ipc_server (IdentityManagerApp* self);
static void identity_manager_app_bus_acquired_cb (IdentityManagerApp* self, GDBusConnection* conn);
MoonshotServer* moonshot_server_new (GtkWindow* window);
MoonshotServer* moonshot_server_construct (GType object_type, GtkWindow* window);
static void _identity_manager_app_bus_acquired_cb_gbus_acquired_callback (GDBusConnection* connection, const char* name, gpointer self);
static void _lambda6_ (GDBusConnection* conn, const char* name, IdentityManagerApp* self);
static void __lambda6__gbus_name_acquired_callback (GDBusConnection* connection, const char* name, gpointer self);
static void _lambda7_ (GDBusConnection* conn, const char* name, IdentityManagerApp* self);
static void __lambda7__gbus_name_lost_callback (GDBusConnection* connection, const char* name, gpointer self);
static void identity_manager_app_finalize (GObject* obj);
gint _vala_main (char** args, int args_length1);



void identity_manager_app_show (IdentityManagerApp* self) {
	g_return_if_fail (self != NULL);
	gtk_widget_show ((GtkWidget*) self->priv->view);
}


IdentityManagerApp* identity_manager_app_construct (GType object_type) {
	IdentityManagerApp * self;
	IdentityManagerModel* _tmp0_;
	IdentityManagerView* _tmp1_;
	self = g_object_newv (object_type, 0, NULL);
	self->model = (_tmp0_ = identity_manager_model_new (self), _g_object_unref0 (self->model), _tmp0_);
	self->priv->view = (_tmp1_ = g_object_ref_sink (identity_manager_view_new (self)), _g_object_unref0 (self->priv->view), _tmp1_);
	identity_manager_app_init_ipc_server (self);
	gtk_widget_show ((GtkWidget*) self->priv->view);
	return self;
}


IdentityManagerApp* identity_manager_app_new (void) {
	return identity_manager_app_construct (TYPE_IDENTITY_MANAGER_APP);
}


static void identity_manager_app_bus_acquired_cb (IdentityManagerApp* self, GDBusConnection* conn) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (conn != NULL);
	{
		moonshot_server_register_object (self->priv->ipc_server, conn, "/org/janet/moonshot", &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			fprintf (stderr, "%s\n", e->message);
			_g_error_free0 (e);
		}
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void _identity_manager_app_bus_acquired_cb_gbus_acquired_callback (GDBusConnection* connection, const char* name, gpointer self) {
	identity_manager_app_bus_acquired_cb (self, connection);
}


static void _lambda6_ (GDBusConnection* conn, const char* name, IdentityManagerApp* self) {
	g_return_if_fail (conn != NULL);
	g_return_if_fail (name != NULL);
}


static void __lambda6__gbus_name_acquired_callback (GDBusConnection* connection, const char* name, gpointer self) {
	_lambda6_ (connection, name, self);
}


static void _lambda7_ (GDBusConnection* conn, const char* name, IdentityManagerApp* self) {
	g_return_if_fail (conn != NULL);
	g_return_if_fail (name != NULL);
	g_error ("moonshot-identity-manager-app.vala:78: Couldn't own name %s on DBus.", name);
}


static void __lambda7__gbus_name_lost_callback (GDBusConnection* connection, const char* name, gpointer self) {
	_lambda7_ (connection, name, self);
}


static void identity_manager_app_init_ipc_server (IdentityManagerApp* self) {
	MoonshotServer* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->ipc_server = (_tmp0_ = moonshot_server_new ((GtkWindow*) self->priv->view), _g_object_unref0 (self->priv->ipc_server), _tmp0_);
	g_bus_own_name_with_closures (G_BUS_TYPE_SESSION, "org.janet.Moonshot", G_BUS_NAME_OWNER_FLAGS_NONE, (GClosure*) g_cclosure_new ((GCallback) _identity_manager_app_bus_acquired_cb_gbus_acquired_callback, g_object_ref (self), g_object_unref), (GClosure*) g_cclosure_new ((GCallback) __lambda6__gbus_name_acquired_callback, g_object_ref (self), g_object_unref), (GClosure*) g_cclosure_new ((GCallback) __lambda7__gbus_name_lost_callback, g_object_ref (self), g_object_unref));
}


static void identity_manager_app_class_init (IdentityManagerAppClass * klass) {
	identity_manager_app_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (IdentityManagerAppPrivate));
	G_OBJECT_CLASS (klass)->finalize = identity_manager_app_finalize;
}


static void identity_manager_app_instance_init (IdentityManagerApp * self) {
	self->priv = IDENTITY_MANAGER_APP_GET_PRIVATE (self);
}


static void identity_manager_app_finalize (GObject* obj) {
	IdentityManagerApp * self;
	self = IDENTITY_MANAGER_APP (obj);
	_g_object_unref0 (self->model);
	_g_object_unref0 (self->priv->view);
	_g_object_unref0 (self->priv->ipc_server);
	G_OBJECT_CLASS (identity_manager_app_parent_class)->finalize (obj);
}


GType identity_manager_app_get_type (void) {
	static volatile gsize identity_manager_app_type_id__volatile = 0;
	if (g_once_init_enter (&identity_manager_app_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (IdentityManagerAppClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) identity_manager_app_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (IdentityManagerApp), 0, (GInstanceInitFunc) identity_manager_app_instance_init, NULL };
		GType identity_manager_app_type_id;
		identity_manager_app_type_id = g_type_register_static (GTK_TYPE_WINDOW, "IdentityManagerApp", &g_define_type_info, 0);
		g_once_init_leave (&identity_manager_app_type_id__volatile, identity_manager_app_type_id);
	}
	return identity_manager_app_type_id__volatile;
}


gint _vala_main (char** args, int args_length1) {
	gint result = 0;
	IdentityManagerApp* app;
	gtk_init (&args_length1, &args);
	fprintf (stdout, "Hello\n");
	{
		char** arg_collection;
		int arg_collection_length1;
		int arg_it;
		arg_collection = args;
		arg_collection_length1 = args_length1;
		for (arg_it = 0; arg_it < args_length1; arg_it = arg_it + 1) {
			char* arg;
			arg = g_strdup (arg_collection[arg_it]);
			{
				fprintf (stdout, "arg %s\n", arg);
				_g_free0 (arg);
			}
		}
	}
	bindtextdomain (GETTEXT_PACKAGE, LOCALEDIR);
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
	textdomain (GETTEXT_PACKAGE);
	app = g_object_ref_sink (identity_manager_app_new ());
	identity_manager_app_show (app);
	gtk_main ();
	result = 0;
	_g_object_unref0 (app);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return _vala_main (argv, argc);
}




