/* moonshot-idcard-widget.c generated by valac 0.10.4, the Vala compiler
 * generated from moonshot-idcard-widget.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <string.h>
#include <gdk/gdk.h>
#include <stdlib.h>
#include <gdk-pixbuf/gdk-pixdata.h>
#include <float.h>
#include <math.h>
#include <glib/gi18n-lib.h>
#include <atk/atk.h>


#define TYPE_ID_CARD_WIDGET (id_card_widget_get_type ())
#define ID_CARD_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ID_CARD_WIDGET, IdCardWidget))
#define ID_CARD_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ID_CARD_WIDGET, IdCardWidgetClass))
#define IS_ID_CARD_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ID_CARD_WIDGET))
#define IS_ID_CARD_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ID_CARD_WIDGET))
#define ID_CARD_WIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ID_CARD_WIDGET, IdCardWidgetClass))

typedef struct _IdCardWidget IdCardWidget;
typedef struct _IdCardWidgetClass IdCardWidgetClass;
typedef struct _IdCardWidgetPrivate IdCardWidgetPrivate;

#define TYPE_ID_CARD (id_card_get_type ())
#define ID_CARD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ID_CARD, IdCard))
#define ID_CARD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ID_CARD, IdCardClass))
#define IS_ID_CARD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ID_CARD))
#define IS_ID_CARD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ID_CARD))
#define ID_CARD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ID_CARD, IdCardClass))

typedef struct _IdCard IdCard;
typedef struct _IdCardClass IdCardClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _IdCardWidget {
	GtkBox parent_instance;
	IdCardWidgetPrivate * priv;
};

struct _IdCardWidgetClass {
	GtkBoxClass parent_class;
};

struct _IdCardWidgetPrivate {
	IdCard* _id_card;
	GtkVBox* main_vbox;
	GtkTable* table;
	GtkButton* _delete_button;
	GtkButton* _details_button;
	GtkButton* _send_button;
	GtkHButtonBox* hbutton_box;
	GtkEventBox* event_box;
};


static gpointer id_card_widget_parent_class = NULL;

GType id_card_widget_get_type (void) G_GNUC_CONST;
GType id_card_get_type (void) G_GNUC_CONST;
#define ID_CARD_WIDGET_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_ID_CARD_WIDGET, IdCardWidgetPrivate))
enum  {
	ID_CARD_WIDGET_DUMMY_PROPERTY,
	ID_CARD_WIDGET_ID_CARD,
	ID_CARD_WIDGET_DELETE_BUTTON,
	ID_CARD_WIDGET_DETAILS_BUTTON,
	ID_CARD_WIDGET_SEND_BUTTON
};
void id_card_widget_collapse (IdCardWidget* self);
static void id_card_widget_set_idcard_color (IdCardWidget* self);
static gboolean id_card_widget_button_press_cb (IdCardWidget* self);
static void id_card_widget_delete_button_cb (IdCardWidget* self);
static void id_card_widget_details_button_cb (IdCardWidget* self);
static void id_card_widget_send_button_cb (IdCardWidget* self);
IdCardWidget* id_card_widget_new (IdCard* id_card);
IdCardWidget* id_card_widget_construct (GType object_type, IdCard* id_card);
void id_card_widget_set_id_card (IdCardWidget* self, IdCard* value);
GdkPixbuf* id_card_get_pixbuf (IdCard* self);
IdCard* id_card_widget_get_id_card (IdCardWidget* self);
const char* id_card_get_issuer (IdCard* self);
char** id_card_get_services (IdCard* self, int* result_length1);
static void id_card_widget_set_delete_button (IdCardWidget* self, GtkButton* value);
static void id_card_widget_set_details_button (IdCardWidget* self, GtkButton* value);
static void id_card_widget_set_send_button (IdCardWidget* self, GtkButton* value);
static void id_card_widget_set_atk_name_description (IdCardWidget* self, GtkWidget* widget, const char* name, const char* description);
GtkButton* id_card_widget_get_delete_button (IdCardWidget* self);
GtkButton* id_card_widget_get_details_button (IdCardWidget* self);
GtkButton* id_card_widget_get_send_button (IdCardWidget* self);
static void _id_card_widget_delete_button_cb_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void _id_card_widget_details_button_cb_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void _id_card_widget_send_button_cb_gtk_button_clicked (GtkButton* _sender, gpointer self);
static gboolean _id_card_widget_button_press_cb_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static void id_card_widget_finalize (GObject* obj);
static void id_card_widget_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void id_card_widget_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);



void id_card_widget_collapse (IdCardWidget* self) {
	g_return_if_fail (self != NULL);
	gtk_widget_set_visible ((GtkWidget*) self->priv->hbutton_box, FALSE);
	id_card_widget_set_idcard_color (self);
}


static gboolean id_card_widget_button_press_cb (IdCardWidget* self) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	gtk_widget_set_visible ((GtkWidget*) self->priv->hbutton_box, !gtk_widget_get_visible ((GtkWidget*) self->priv->hbutton_box));
	id_card_widget_set_idcard_color (self);
	if (gtk_widget_get_visible ((GtkWidget*) self->priv->hbutton_box) == TRUE) {
		g_signal_emit_by_name (self, "expanded");
	}
	result = FALSE;
	return result;
}


static void id_card_widget_delete_button_cb (IdCardWidget* self) {
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "remove-id");
}


static void id_card_widget_details_button_cb (IdCardWidget* self) {
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "details-id");
}


static void id_card_widget_send_button_cb (IdCardWidget* self) {
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "send-id");
}


static void id_card_widget_set_idcard_color (IdCardWidget* self) {
	GdkColor color = {0};
	GtkStateType state;
	g_return_if_fail (self != NULL);
	memset (&color, 0, sizeof (GdkColor));
	if (gtk_widget_get_visible ((GtkWidget*) self->priv->hbutton_box) == FALSE) {
		color.red = (guint16) 65535;
		color.green = (guint16) 65535;
		color.blue = (guint16) 65535;
	} else {
		color.red = (guint16) 33333;
		color.green = (guint16) 33333;
		color.blue = (guint16) 60000;
	}
	state = gtk_widget_get_state ((GtkWidget*) self);
	gtk_widget_modify_bg ((GtkWidget*) self->priv->event_box, state, &color);
}


static void _id_card_widget_delete_button_cb_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	id_card_widget_delete_button_cb (self);
}


static void _id_card_widget_details_button_cb_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	id_card_widget_details_button_cb (self);
}


static void _id_card_widget_send_button_cb_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	id_card_widget_send_button_cb (self);
}


static gboolean _id_card_widget_button_press_cb_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = id_card_widget_button_press_cb (self);
	return result;
}


IdCardWidget* id_card_widget_construct (GType object_type, IdCard* id_card) {
	IdCardWidget * self;
	char* services_text;
	GtkImage* image;
	char* issuer;
	char* _tmp3_;
	char* _tmp4_;
	char* text;
	GtkLabel* id_data_label;
	GtkTable* _tmp5_;
	GtkButton* _tmp6_;
	GtkButton* _tmp7_;
	GtkButton* _tmp8_;
	GtkHButtonBox* _tmp9_;
	GtkVBox* _tmp10_;
	GtkEventBox* _tmp11_;
	g_return_val_if_fail (id_card != NULL, NULL);
	self = g_object_newv (object_type, 0, NULL);
	services_text = g_strdup ("");
	id_card_widget_set_id_card (self, id_card);
	image = g_object_ref_sink ((GtkImage*) gtk_image_new_from_pixbuf (id_card_get_pixbuf (id_card)));
	issuer = g_markup_printf_escaped ("<b>%s</b>", id_card_get_issuer (self->priv->_id_card));
	{
		gint _tmp0_;
		char** service_collection;
		int service_collection_length1;
		int service_it;
		service_collection = id_card_get_services (id_card, &_tmp0_);
		service_collection_length1 = _tmp0_;
		for (service_it = 0; service_it < _tmp0_; service_it = service_it + 1) {
			char* service;
			service = g_strdup (service_collection[service_it]);
			{
				char* _tmp1_;
				char* _tmp2_;
				services_text = (_tmp2_ = g_strconcat (services_text, _tmp1_ = g_markup_printf_escaped ("<i>%s, </i>", service), NULL), _g_free0 (services_text), _tmp2_);
				_g_free0 (_tmp1_);
				_g_free0 (service);
			}
		}
	}
	text = (_tmp4_ = g_strconcat (_tmp3_ = g_strconcat (issuer, "\n", NULL), services_text, NULL), _g_free0 (_tmp3_), _tmp4_);
	id_data_label = g_object_ref_sink ((GtkLabel*) gtk_label_new (NULL));
	gtk_label_set_markup (id_data_label, text);
	gtk_misc_set_alignment ((GtkMisc*) id_data_label, (float) 0, (float) 0.5);
	self->priv->table = (_tmp5_ = g_object_ref_sink ((GtkTable*) gtk_table_new ((guint) 1, (guint) 2, FALSE)), _g_object_unref0 (self->priv->table), _tmp5_);
	gtk_table_attach_defaults (self->priv->table, (GtkWidget*) image, (guint) 0, (guint) 1, (guint) 0, (guint) 1);
	gtk_table_attach_defaults (self->priv->table, (GtkWidget*) id_data_label, (guint) 1, (guint) 2, (guint) 0, (guint) 1);
	id_card_widget_set_delete_button (self, _tmp6_ = g_object_ref_sink ((GtkButton*) gtk_button_new_with_label (_ ("Delete"))));
	_g_object_unref0 (_tmp6_);
	id_card_widget_set_details_button (self, _tmp7_ = g_object_ref_sink ((GtkButton*) gtk_button_new_with_label (_ ("View details"))));
	_g_object_unref0 (_tmp7_);
	id_card_widget_set_send_button (self, _tmp8_ = g_object_ref_sink ((GtkButton*) gtk_button_new_with_label (_ ("Send"))));
	_g_object_unref0 (_tmp8_);
	id_card_widget_set_atk_name_description (self, (GtkWidget*) self->priv->_delete_button, _ ("Delete"), _ ("Delete this ID Card"));
	id_card_widget_set_atk_name_description (self, (GtkWidget*) self->priv->_details_button, _ ("Details"), _ ("View the details of this ID Card"));
	id_card_widget_set_atk_name_description (self, (GtkWidget*) self->priv->_send_button, _ ("Send"), _ ("Send this ID Card"));
	self->priv->hbutton_box = (_tmp9_ = g_object_ref_sink ((GtkHButtonBox*) gtk_hbutton_box_new ()), _g_object_unref0 (self->priv->hbutton_box), _tmp9_);
	gtk_box_pack_end ((GtkBox*) self->priv->hbutton_box, (GtkWidget*) self->priv->_delete_button, TRUE, TRUE, 0);
	gtk_box_pack_end ((GtkBox*) self->priv->hbutton_box, (GtkWidget*) self->priv->_details_button, TRUE, TRUE, 0);
	gtk_box_pack_end ((GtkBox*) self->priv->hbutton_box, (GtkWidget*) self->priv->_send_button, TRUE, TRUE, 0);
	g_signal_connect_object (self->priv->_delete_button, "clicked", (GCallback) _id_card_widget_delete_button_cb_gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->_details_button, "clicked", (GCallback) _id_card_widget_details_button_cb_gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->_send_button, "clicked", (GCallback) _id_card_widget_send_button_cb_gtk_button_clicked, self, 0);
	self->priv->main_vbox = (_tmp10_ = g_object_ref_sink ((GtkVBox*) gtk_vbox_new (FALSE, 12)), _g_object_unref0 (self->priv->main_vbox), _tmp10_);
	gtk_box_pack_start ((GtkBox*) self->priv->main_vbox, (GtkWidget*) self->priv->table, TRUE, TRUE, (guint) 0);
	gtk_box_pack_start ((GtkBox*) self->priv->main_vbox, (GtkWidget*) self->priv->hbutton_box, FALSE, FALSE, (guint) 0);
	gtk_container_set_border_width ((GtkContainer*) self->priv->main_vbox, (guint) 12);
	self->priv->event_box = (_tmp11_ = g_object_ref_sink ((GtkEventBox*) gtk_event_box_new ()), _g_object_unref0 (self->priv->event_box), _tmp11_);
	gtk_container_add ((GtkContainer*) self->priv->event_box, (GtkWidget*) self->priv->main_vbox);
	g_signal_connect_object ((GtkWidget*) self->priv->event_box, "button-press-event", (GCallback) _id_card_widget_button_press_cb_gtk_widget_button_press_event, self, 0);
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) self->priv->event_box, TRUE, TRUE, 0);
	gtk_widget_show_all ((GtkWidget*) self);
	gtk_widget_hide ((GtkWidget*) self->priv->hbutton_box);
	id_card_widget_set_idcard_color (self);
	_g_object_unref0 (id_data_label);
	_g_free0 (text);
	_g_free0 (issuer);
	_g_object_unref0 (image);
	_g_free0 (services_text);
	return self;
}


IdCardWidget* id_card_widget_new (IdCard* id_card) {
	return id_card_widget_construct (TYPE_ID_CARD_WIDGET, id_card);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void id_card_widget_set_atk_name_description (IdCardWidget* self, GtkWidget* widget, const char* name, const char* description) {
	AtkObject* atk_widget;
	g_return_if_fail (self != NULL);
	g_return_if_fail (widget != NULL);
	g_return_if_fail (name != NULL);
	g_return_if_fail (description != NULL);
	atk_widget = _g_object_ref0 (gtk_widget_get_accessible (widget));
	atk_object_set_name (atk_widget, name);
	atk_object_set_description (atk_widget, description);
	_g_object_unref0 (atk_widget);
}


IdCard* id_card_widget_get_id_card (IdCardWidget* self) {
	IdCard* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_id_card;
	return result;
}


void id_card_widget_set_id_card (IdCardWidget* self, IdCard* value) {
	IdCard* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_id_card = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_id_card), _tmp0_);
	g_object_notify ((GObject *) self, "id-card");
}


GtkButton* id_card_widget_get_delete_button (IdCardWidget* self) {
	GtkButton* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_delete_button;
	return result;
}


static void id_card_widget_set_delete_button (IdCardWidget* self, GtkButton* value) {
	GtkButton* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_delete_button = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_delete_button), _tmp0_);
	g_object_notify ((GObject *) self, "delete-button");
}


GtkButton* id_card_widget_get_details_button (IdCardWidget* self) {
	GtkButton* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_details_button;
	return result;
}


static void id_card_widget_set_details_button (IdCardWidget* self, GtkButton* value) {
	GtkButton* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_details_button = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_details_button), _tmp0_);
	g_object_notify ((GObject *) self, "details-button");
}


GtkButton* id_card_widget_get_send_button (IdCardWidget* self) {
	GtkButton* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_send_button;
	return result;
}


static void id_card_widget_set_send_button (IdCardWidget* self, GtkButton* value) {
	GtkButton* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_send_button = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_send_button), _tmp0_);
	g_object_notify ((GObject *) self, "send-button");
}


static void id_card_widget_class_init (IdCardWidgetClass * klass) {
	id_card_widget_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (IdCardWidgetPrivate));
	G_OBJECT_CLASS (klass)->get_property = id_card_widget_get_property;
	G_OBJECT_CLASS (klass)->set_property = id_card_widget_set_property;
	G_OBJECT_CLASS (klass)->finalize = id_card_widget_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), ID_CARD_WIDGET_ID_CARD, g_param_spec_object ("id-card", "id-card", "id-card", TYPE_ID_CARD, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ID_CARD_WIDGET_DELETE_BUTTON, g_param_spec_object ("delete-button", "delete-button", "delete-button", GTK_TYPE_BUTTON, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ID_CARD_WIDGET_DETAILS_BUTTON, g_param_spec_object ("details-button", "details-button", "details-button", GTK_TYPE_BUTTON, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ID_CARD_WIDGET_SEND_BUTTON, g_param_spec_object ("send-button", "send-button", "send-button", GTK_TYPE_BUTTON, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_signal_new ("expanded", TYPE_ID_CARD_WIDGET, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("remove_id", TYPE_ID_CARD_WIDGET, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("details_id", TYPE_ID_CARD_WIDGET, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("send_id", TYPE_ID_CARD_WIDGET, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void id_card_widget_instance_init (IdCardWidget * self) {
	self->priv = ID_CARD_WIDGET_GET_PRIVATE (self);
	self->priv->_id_card = NULL;
	self->priv->_delete_button = NULL;
	self->priv->_details_button = NULL;
	self->priv->_send_button = NULL;
}


static void id_card_widget_finalize (GObject* obj) {
	IdCardWidget * self;
	self = ID_CARD_WIDGET (obj);
	_g_object_unref0 (self->priv->_id_card);
	_g_object_unref0 (self->priv->main_vbox);
	_g_object_unref0 (self->priv->table);
	_g_object_unref0 (self->priv->_delete_button);
	_g_object_unref0 (self->priv->_details_button);
	_g_object_unref0 (self->priv->_send_button);
	_g_object_unref0 (self->priv->hbutton_box);
	_g_object_unref0 (self->priv->event_box);
	G_OBJECT_CLASS (id_card_widget_parent_class)->finalize (obj);
}


GType id_card_widget_get_type (void) {
	static volatile gsize id_card_widget_type_id__volatile = 0;
	if (g_once_init_enter (&id_card_widget_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (IdCardWidgetClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) id_card_widget_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (IdCardWidget), 0, (GInstanceInitFunc) id_card_widget_instance_init, NULL };
		GType id_card_widget_type_id;
		id_card_widget_type_id = g_type_register_static (GTK_TYPE_BOX, "IdCardWidget", &g_define_type_info, 0);
		g_once_init_leave (&id_card_widget_type_id__volatile, id_card_widget_type_id);
	}
	return id_card_widget_type_id__volatile;
}


static void id_card_widget_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	IdCardWidget * self;
	self = ID_CARD_WIDGET (object);
	switch (property_id) {
		case ID_CARD_WIDGET_ID_CARD:
		g_value_set_object (value, id_card_widget_get_id_card (self));
		break;
		case ID_CARD_WIDGET_DELETE_BUTTON:
		g_value_set_object (value, id_card_widget_get_delete_button (self));
		break;
		case ID_CARD_WIDGET_DETAILS_BUTTON:
		g_value_set_object (value, id_card_widget_get_details_button (self));
		break;
		case ID_CARD_WIDGET_SEND_BUTTON:
		g_value_set_object (value, id_card_widget_get_send_button (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void id_card_widget_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	IdCardWidget * self;
	self = ID_CARD_WIDGET (object);
	switch (property_id) {
		case ID_CARD_WIDGET_ID_CARD:
		id_card_widget_set_id_card (self, g_value_get_object (value));
		break;
		case ID_CARD_WIDGET_DELETE_BUTTON:
		id_card_widget_set_delete_button (self, g_value_get_object (value));
		break;
		case ID_CARD_WIDGET_DETAILS_BUTTON:
		id_card_widget_set_details_button (self, g_value_get_object (value));
		break;
		case ID_CARD_WIDGET_SEND_BUTTON:
		id_card_widget_set_send_button (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}




